version: '3.4'

services:
  order-reactui:
    build:
      context: .
      dockerfile: src/React-web-ui/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - kafka-connection.env
  order-api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile   
    ports:
     - "5000:5000"
    env_file:
      - kafka-connection.env
      
  hostedservice-mixing:
    build:
      context: .
      dockerfile: src/Services/Service.Mixing/Dockerfile   
    ports:
     - "5001:5001"
    env_file:
      - kafka-connection.env
  
  hostedservice-baking:
    build:
      context: .
      dockerfile: src/Services/Service.Baking/Dockerfile   
    ports:
     - "5002:5002"
    env_file:
      - kafka-connection.env
  
  hostedservice-decorating:
    build:
      context: .
      dockerfile: src/Services/Service.Decorating/Dockerfile   
    ports:
     - "5003:5003"
    env_file:
      - kafka-connection.env
  
  hostedservice-packaging:
    build:
      context: .
      dockerfile: src/Services/Service.Packaging/Dockerfile   
    ports:
     - "5004:5004"
    env_file:
      - kafka-connection.env